version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install --upgrade pdm
      - VIRTUAL_ENV=$(dirname $(dirname $(which python))) pdm install -dG doc
