name: deps_from_conda

on:
  workflow_run:
    workflows:
      - lint_and_tests
    types:
      - completed
jobs:
  deps_from_conda:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
      - run: conda install -c conda-forge pinocchio robomeshcat example-robot-data matplotlib numpy pycollada shapely anytree ruff black pytest
      - run: pip install --no-deps -e .
      - run: pytest tests/test_geometry_utils.py
#      - run: pytest tests/
#      - run: pytest tests/hw01/mandatory
#      - run: pytest tests/hw02/mandatory
