name: lint_and_tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pdm install
      - run: pdm lint
      - run: pdm pytest tests/test_geometry_utils.py
#      - run: pdm test # this will run all the tests, but it is necessary to finish
#        # the implementation of template for it to work
