name: linux_in_conda


on:
  push:
    branches:
      - main
  pull_request:
#on:
#  workflow_run:
#    workflows:
#      - lint_and_tests
#    types:
#      - completed
jobs:
  linux_in_conda:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
      - run: conda install 'pdm>=2.15'
      - run: pdm --version
      - run: pdm install -vv
      - run: ruff check robotics_toolbox
      - run: black --check --diff --verbose robotics_toolbox
      - run: pytest tests/test_geometry_utils.py
#      - run: pytest tests/
#      - run: pytest tests/hw01/mandatory
#      - run: pytest tests/hw02/mandatory
