name: trigger_rtd

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
